version: '3'
services:
  # InfluxDB: https://hub.docker.com/_/influxdb
  influxdb:
    image: influxdb:2.1
    profiles: ["test_case_1"]
    ports:
      - 8042:8042
    volumes:
      - ./storage/influxdb:/var/lib/influxdb2 #this will be mounted
      - ./configs/influx:/etc/influx/
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
      - INFLUXD_CONFIG_PATH=/etc/influx/config.yaml
    restart: on-failure:10
    networks:
      - iot-emulator
  # add mosquitto service
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    user: 1000:1000
    profiles: ["test_case_1"]
    volumes:
      - ./storage/mosquitto/log:/mosquitto/log
      - ./storage/mosquitto/data:/mosquitto/data
      - ./configs/mosquitto:/mosquitto/config/
    ports:
      - 1883:1883
    restart: on-failure:10
    networks:
      - iot-emulator
  # add gateway services
  gateway1:
    image:  gateway
    profiles: ["test_case_1"]
    volumes:
      - ./configs/gateway1:/gateway/config/
      - ./storage/gateway1/log:/gateway/log/
      - ./storage/gateway1/csv:/gateway/csv/
    entrypoint: ["/gateway/docker_build/LoraGateway",
                 "--config=/gateway/config/for_docker.json"]
    restart: on-failure
    networks:
      - iot-emulator
  gateway2:
    image:  gateway
    profiles: ["test_case_1"]
    volumes:
      - ./configs/gateway2:/gateway/config/
      - ./storage/gateway2/log:/gateway/log/
      - ./storage/gateway2/csv:/gateway/csv/
    entrypoint: ["/gateway/docker_build/LoraGateway",
                 "--config=/gateway/config/for_docker.json"]
    restart: on-failure
    networks:
      - iot-emulator
  gateway3:
    image:  gateway
    profiles: ["test_case_1"]
    volumes:
      - ./configs/gateway3:/gateway/config/
      - ./storage/gateway3/log:/gateway/log/
      - ./storage/gateway3/csv:/gateway/csv/
    entrypoint: ["/gateway/docker_build/LoraGateway",
                 "--config=/gateway/config/for_docker.json"]
    restart: on-failure
    networks:
      - iot-emulator
  # add uploader service
  uploader:
    image:  uploader
    user: 1000:1000
    profiles: ["test_case_1"]
    volumes:
      - ./configs/uploader:/uploader/config/
    entrypoint: ["python3", "main.py",
                 "-c", "/uploader/config/for_docker.json"]
    restart: on-failure:10
    depends_on:
      - mariadb
      - influxdb
    networks:
      - iot-emulator
  # add mariadb service
  mariadb:
    image: mariadb:latest
    profiles: ["test_case_1"]
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - ./storage/mariadb-data:/var/lib/mysql
      - ./configs/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure:10
    networks:
      - iot-emulator

  # Add Adminer service
  adminer:
    image: adminer
    profiles: ["test_case_1"]
    ports:
      - 59452:8080
    links:
      - mariadb
    restart: on-failure:10
    networks:
      - iot-emulator

networks:
  iot-emulator:
    name: iot-emulator
